### ISSUE TITLE
Can i help you adding ET-4700 ?

### ISSUE THREAD

**Issue by DonKiShoot** [Ircama/epson_print_conf#12]
Hello,

I have the issue where waste ink block the printer.
I tried your tool but apparently this doesn't work.

[INFO] Detecting printers... (this might take a while)
[ERROR] 'utf-8' codec can't decode byte 0x88 in position 18: invalid start byte

Version windows 2.1.28

Regards,

**Comment by Ircama** [comment]
Please try now v2.1.30

**Comment by DonKiShoot** [comment]
Detection seems ok now : 

[INFO] Detecting printers... (this might take a while)
[INFO] Found printer 'EPSON ET-4700 Series' at 192.168.1.17 (hostname: epson8177c2.home)

I will try the others functions :)

Thank for your rapidity ;-)

**Comment by DonKiShoot** [comment]
"Power-off timer get" gave : 

[ERROR] Please select a printer model and a valid IP address, or press 'Detect Printers'.

**Comment by DonKiShoot** [comment]
Same for "TI Received Time" : 

[ERROR] Please select a printer model and a valid IP address, or press 'Detect Printers'.

**Comment by DonKiShoot** [comment]
Printer status seems working (i didn't capture all voluntarily)

![image](https://github.com/user-attachments/assets/704cd3d9-1aa5-4ca7-aaaf-a6ddaf3a9b7c)

**Comment by DonKiShoot** [comment]
![image](https://github.com/user-attachments/assets/7ce4008f-6c6f-4127-b71c-112633dda68c)

![image](https://github.com/user-attachments/assets/5ee32990-9231-47e6-9c66-f2d7fa9f36bd)

Only "IP Address" and "Power Off Timer" values are missing (it s empty)

**Comment by DonKiShoot** [comment]
"Reset Waste Lnk Levels" seems not working :-(

[INFO] Detecting printers... (this might take a while)
[INFO] Found printer 'EPSON ET-4700 Series' at 192.168.1.17 (hostname: epson8177c2.home)
[ERROR] Please select a printer model and a valid IP address, or press 'Detect Printers'.
[ERROR] Please select a printer model and a valid IP address, or press 'Detect Printers'.
[ERROR] Please select a printer model and a valid IP address, or press 'Detect Printers'.
