### ISSUE TITLE
ET-4700 recognized but 'Rst Waste Lnk Lvl' doesn't work

### ISSUE THREAD

**Issue by DonKiShoot** [Ircama/epson_print_conf#13]
Hello,

How can i help you to debug this function on ET-4700 ?

[INFO] Found printer 'EPSON ET-4700 Series' at 192.168.1.17 (hostname: epson8177c2.home)

When i click "Reset Waste Lnk Level" this is what i got : 

[ERROR] Please select a printer model and a valid IP address, or press 'Detect Printers'.

Regards,

**Comment by Ircama** [comment]
Please check latest version v2.1.31

**Comment by DonKiShoot** [comment]
At first sight it worked.
No more error message at boot for my printer.
I hope everything will still work as before :-)
I'm very happy cause my wife will be glad this evening being able finishing printing the children's courses for their return to school this monday

I already ordered the replacement part to avoid futur uncorrectable issue (non software).

Thank you so much you saved my printer and my wedding =D

**Comment by DonKiShoot** [comment]
Stable since v2.1.31, i close this issue

**Comment by DonKiShoot** [comment]
Stable since v2.1.31, i close this issue
