### ISSUE TITLE
Ink PAD Counter Reset Not Happening 

### ISSUE THREAD

**Issue by vkabcd** [Ircama/epson_print_conf#15]
![Printer Status](https://github.com/user-attachments/assets/8baddf97-d11a-4314-a524-87916ff58ab2)
The app is able to find the printer, and reset worked as per message, but still printer boot with message "printer ink pad is end of service life", any suggestions to reset. Ref attached image.

[INFO] Detecting printers... (this might take a while)
[INFO] Found printer 'EPSON XP-820 Series' at 192.168.1.147 (hostname: EPSON09BE09)
[INFO] Waste ink levels have been reset. Perform a power cycle of the printer now.
[ERROR]: Missing 'Power off timer' in configuration
[ERROR]: Missing 'First TI received time' in configuration
[INFO] Waste ink levels have been reset. Perform a power cycle of the printer now.
[INFO] Waste ink levels have been reset. Perform a power cycle of the printer now.

**Comment by Ircama** [comment]
Please try now

**Comment by vkabcd** [comment]
Great... It Worked Flawlessly... Thank you,
