### ISSUE TITLE
Epson L5190 is "detected" by prog but I can't find it in dropdown list

### ISSUE THREAD

**Issue by Mopple128** [Ircama/epson_print_conf#17]
Hi, 

thanks for that great prog "Epson Config Tool"; 

Big problem is: My L5190 is detected when I click on "detect printers", "Printer Status" works, everything is displayed but when I try to "reset waste ink levels" it always wants me to choose a printer model from the dropdown list but the l5190 is not included there and that's it - "error". 

Am I missing something? Can anybody help me? Thanks in advance!

**Comment by Ircama** [comment]
Printer not (yet) included in the configuration. Please [try to integrate it yourself](https://github.com/Ircama/epson_print_conf/?tab=readme-ov-file#example-to-integrate-new-printers).
