### ISSUE TITLE
XP-445 recognized but 'Rst Waste Lnk Lvl' doesn't work

### ISSUE THREAD

**Issue by Miilooo** [Ircama/epson_print_conf#18]
Hello,

I have the exact same problem as the issue #13 but with an XP-445.

Im actually using the v2.1.32 and I have this messages :

[INFO] Found printer 'EPSON XP-442 445 Series' at 192.168.1.92 (hostname: EPSON8F7DB3)

*Reset Waste Ink Levels"

[ERROR] Please select a printer model and a valid IP address, or press 'Detect Printers'.

Can you help me please ?

Thanks

**Comment by Ircama** [comment]
Printer not (yet) included in the configuration. Please [try to integrate it yourself](https://github.com/Ircama/epson_print_conf/?tab=readme-ov-file#example-to-integrate-new-printers).
