### ISSUE TITLE
Borderless ink pad Epson ET-16650

### ISSUE THREAD

**Issue by Virusmater** [Ircama/epson_print_conf#19]
I have following error with my printer:
```
You cannot print borderless until the printer's borderless printing ink pad is replaced. The ink pad is not user-replaceable. Please contact Epson support.

You can still print when not using the borderless printing feature.
```
Printer is detected, but not supported:
```
[INFO] Found printer 'EPSON ET-16650 Series' at 192.168.1.100 (hostname: EPSON794D1C)
```
![image](https://github.com/user-attachments/assets/7f64c11d-abfa-4145-863f-0c62cccaefd3)
![image](https://github.com/user-attachments/assets/d6f5cf03-80fb-47d8-9bd6-11403c62f80a)
![image](https://github.com/user-attachments/assets/4f11ceab-3455-4ba1-8b46-d907c2c95e8e)
![image](https://github.com/user-attachments/assets/6040dadd-f48e-4f38-bf2d-40f7f1268438)
![image](https://github.com/user-attachments/assets/1ffdc0ad-d758-49c4-80f2-b5559ec809e1)

Any idea if I can reset **borderless** printing ink pad? I tried to run using different printer model and do the reset, but it didn't work

**Comment by Ircama** [comment]
Printer ET-16650 is not defined in [epson_print_conf.py](/Ircama/epson_print_conf/blob/main/epson_print_conf.py).

Have you tried using [parse_devices.py](https://github.com/Ircama/epson_print_conf?tab=readme-ov-file#parse_devicespy)?

**Comment by Virusmater** [comment]
Sorry, I cannot check anymore, I did the reset with Wic
