### ISSUE TITLE
Trying to Add new printer

### ISSUE THREAD

**Issue by MaxKreimerman** [Ircama/epson_print_conf#20]
Hi,
First, big thanks for the software, brilliant.

I am trying to add EPSON XP-442 445 Series to the options but I dont know the codes for the WIC, any idea on how can get those?

**Comment by Ircama** [comment]
> Hi, First, big thanks for the software, brilliant.
> 
> I am trying to add EPSON XP-442 445 Series to the options but I dont know the codes for the WIC, any idea on how can get those?

Have you tried using [parse_devices.py](https://github.com/Ircama/epson_print_conf?tab=readme-ov-file#parse_devicespy)?
