### ISSUE TITLE
when trying to reset the level of used ink, it gives an error

### ISSUE THREAD

**Issue by LAYZ1HAG** [Ircama/epson_print_conf#21]
![изображение_2024-09-18_172850113](https://github.com/user-attachments/assets/76fa590f-f82b-4024-a282-fbfbe6d9597e)
Please help me, what am I doing wrong?

**Comment by Ircama** [comment]
Please try with version 2.2.1

**Comment by LAYZ1HAG** [comment]
for some reason, the new version of the program did not run through the exe, I was able to run it using python and got the same error
![image](https://github.com/user-attachments/assets/b73aa769-7d91-4405-82eb-69a0989d7bfd)

**Comment by Ircama** [comment]
Please try again with version [v2.2.11](https://github.com/Ircama/epson_print_conf/releases)

**Comment by LAYZ1HAG** [comment]
ok, now the program has started with the exe, and there are explanations for the errors
![image](https://github.com/user-attachments/assets/4c14bb29-0484-461b-a88c-6f01217f1c5c)

**Comment by Ircama** [comment]
This issue should be fixed with v2.2.14.

**Comment by LAYZ1HAG** [comment]
Thanks bro, it's working
